export default interface IBlogData {
  Title: string;
  URL: any;
  Img: any;
  Desc: string;
  Tagname: string[];
  Latest: boolean;
  Featured: boolean;
  Trend: boolean;
  // year?: number | any;
}

export const BlogLists: IBlogData[] = [
  {
    Title: "AI in Service Management Platforms",
    URL: "/AIinServiceManagement",
    Img: "/assets/Blogs/blogheaders/AIinServiceManagement_Header.webp",
    Desc: "AI Powered Chatbots Increase Demand for Service Management Platforms",
    Tagname: ["Cloud Management", "Digisquares Platform"],
    Latest: false,
    Featured: false,
    Trend: false,
  },

  {
    Title: "3 Key Ways Automation Enhances ITSM and Customer Service",
    URL: "/AutomationInITSMandCustomerService",
    Img: "/assets/DatabaseSoftwareMain.webp",
    Desc: "How Automation Can Boost ITSM and Customer Service in 3 Effective Methods",
    Tagname: ["Data Management", "IT Management"],
    Latest: false,
    Featured: false,
    Trend: false,
  },
  {
    Title: "Deploying AI at scale",
    URL: "/Deployingscale",
    Img: "/assets/ezgif.com-gif-maker (2).webp",
    Desc: "the future of manufacturing can be found at FANUC’s plant in Oshino, Japan.",
    Tagname: ["AI and Automation", "IT Management"],
    Latest: false,
    Featured: false,
    Trend: false,
  },

  {
    Title: "Workdays in IT Security",
    URL: "/WorkdaysinITSecurity",
    Img: "/assets/Database Main.webp",
    Desc: "Learn how collaboration and automation reduce long IT security workdays.",
    Tagname: ["Cybersecurity and risk", "Digisquares Platform"],
    Latest: false,
    Featured: false,
    Trend: true,
  },
  {
    Title: "Boosting Cybersecurity",
    URL: "/BoostingCybersecurity",
    Img: "/assets/GovernanceComp.webp",
    Desc: "Learn three key strategies to boost your company’s cybersecurity efforts.",
    Tagname: ["Cybersecurity and risk", "AI and Automation", "Governance"],
    Latest: false,
    Featured: false,
    Trend: false,
  },

  {
    Title: "Transforming Your Business",
    URL: "/TransformingYourBusiness",
    Img: "/assets/Manageddatabase_3.webp",
    Desc: "3 Steps to Accelerate Digital-First Growth and Streamline Operations",
    Tagname: ["IT Management", "Cybersecurity and risk"],
    Latest: false,
    Featured: false,
    Trend: true,
  },
  {
    Title: "Intelligent Automation in ITSM",
    URL: "/IntelligentAutomationInITSM",
    Img: "/assets/AI-foto-generale.webp",
    Desc: "How AI and Automation Are Modernizing IT Service Management",
    Tagname: ["IT Management", "AI and Automation", "Cybersecurity and risk"],
    Latest: false,
    Featured: false,
    Trend: false,
  },
  {
    Title: "AI-Powered Automation",
    URL: "/AIPoweredAutomation",
    Img: "/assets/Blogs/blogheaders/AIPoweredAutomation_Header.webp",
    Desc: "Learn how to reduce MTTR by streamlining workflows and automating processes",
    Tagname: ["IT Management", "Cybersecurity and risk"],
    Latest: false,
    Featured: false,
    Trend: false,
  },
  {
    Title: "Drag-and-Drop Platforms",
    URL: "/DragandDropPlatforms",
    Img: "/assets/GovernanceComp.webp",
    Desc: "Discover why drag-and-drop platforms are the future of software development",
    Tagname: [
      "IT Management",
      "Cybersecurity and risk",
      "Digisquares Platform",
    ],
    Latest: false,
    Featured: false,
    Trend: false,
  },
  {
    Title: "Solving Business Problems",
    URL: "/SolvingBusinessProblems",
    Img: "/assets/CloudSecurity1.webp",
    Desc: "Unlocking Business Success Through the Digisquares Platform’s Continuous Innovation",
    Tagname: ["IT Management", "Digisquares Platform"],
    Latest: false,
    Featured: false,
    Trend: false,
  },

  // ----------------------------------------------------------------------------------------------------
  // {
  //   Title: "AI tools in real-world",
  //   URL: "/AIToolsforRealWorld",
  //   Img: "/assets/Blogs/blogheaders/AIToolsforRealWorld_Header.webp",
  //   Desc: "Exploring how human involvement enhances AI tools for real-world value",
  //   Tagname: ["AI and Automation", "Cloud Management", "Database Management"],
  //   Latest: true,
  //   Featured: false,
  //   Trend: false,
  //   // year: 2022,
  // },
  {
    Title: "AI and Automation",
    URL: "/DigisquaresAIplatform",
    Img: "/assets/Blogs/blogheaders/DigisquaresAIplatform_Header1.webp",
    Desc: "Should businesses build LLMs or use Digisquares' AI platforms?",
    Tagname: ["AI and Automation", "Cloud Management"],
    Latest: false,
    Featured: true,
    Trend: false,
    // year: 2022,
  },
  {
    Title: "Effective Ways for Business Growth",
    URL: "/WaysforBusinessGrowth",
    Img: "/assets/CloudEnabledAI%20Main.webp",
    Desc: "4 Effective Ways to Harness Digitalization for Business Growth",
    Tagname: ["Cloud Management", "AI and Automation"],
    Latest: false,
    Featured: true,
    Trend: false,
  },
  {
    Title: "Nonprofits using AI Technology",
    URL: "/NonprofitsUsingAI",
    Img: "/assets/DataSecureMainImg.webp",
    Desc: "How Nonprofits Are Using Technology to Drive Change",
    Tagname: ["Digital Transformation", "Digisquares Platform"],
    Latest: false,
    Featured: true,
    Trend: false,
  },
  {
    Title: "Building a Secure SaaS Ecosystem",
    URL: "/ImprovingSAASCybersecurity",
    Img: "/assets/Blogs/blogheaders/ImprovingSAASCybersecurity_Header.webp",
    Desc: "Building a Secure SaaS Ecosystem Through Shared Frameworks and AI",
    Tagname: [
      "Cybersecurity and risk",
      "Digisquares Platform",
      "IT Management",
    ],
    Latest: false,
    Featured: true,
    Trend: false,
  },
  {
    Title: "Team Collaboration with AppStudio",
    URL: "/TeamCollaborationwithAppStudio",
    Img: "/assets/Blogs/blogheaders/TeamCollaborationwithAppStudio_Header.webp",
    Desc: "Enhance Team Collaboration with AppStudio’s Integrated Communication and Development Tools",
    Tagname: ["IT Management", "Database Management"],
    Latest: false,
    Featured: true,
    Trend: false,
  },
  {
    Title: "Future of App Development",
    URL: "/FutureofAppDevelopment",
    Img: "/assets/Blogs/blogheaders/FutureofAppDevelopment_Header.webp",
    Desc: "Transforming App Development with AppStudio: The Low-Code Advantage",
    Tagname: ["IT Management", "Cybersecurity and risk", "Database Management"],
    Latest: true,
    Featured: false,
    Trend: false,
  },
  {
    Title: "From Idea to App",
    URL: "/FromIdeatoApp",
    Img: "/assets/Blogs/blogheaders/FromIdeatoApp_Header.webp",
    Desc: "From Concept to Launch: Real-Life Success with AppStudio",
    Tagname: ["IT Management", "Cybersecurity and risk", "Database Management"],
    Latest: true,
    Featured: false,
    Trend: false,
  },
  {
    Title: "AppStudio’s Security Features",
    URL: "/AppStudioSecurityFeatures",
    Img: "/assets/Blogs/blogheaders/AppStudioSecurityFeatures_Header.webp",
    Desc: "Building Safe Apps: Security Best Practices with AppStudio",
    Tagname: ["IT Management", "Cybersecurity and risk", "Database Management"],
    Latest: false,
    Featured: true,
    Trend: false,
  },
  {
    Title: "Innovation Trends for Business",
    URL: "/InnovationTrendsforBusiness",
    Img: "/assets/Blogs/blogheaders/InnovationTrendsforBusiness_Header.webp",
    Desc: "Explore six innovation trends and their impact on business growth",
    Tagname: ["IT Management", "AI and Automation", "Database Management"],
    Latest: true,
    Featured: false,
    Trend: true,
  },
  {
    Title: "Business with AppStudio",
    URL: "/BusinesswithAppStudio",
    Img: "/assets/Blogs/blogheaders/BusinesswithAppStudio_Header.webp",
    Desc: "Empower Your Growth: The Low-Code Advantage with AppStudio",
    Tagname: ["Cybersecurity and risk"],
    Latest: false,
    Featured: true,
    Trend: false,
  },
  {
    Title: "AI Agents in AppStudio",
    URL: "/AIAgentsinAppStudio",
    Img: "/assets/Blogs/blogheaders/AIAgentsinAppStudio_Header.webp",
    Desc: "How AI Agents in AppStudio Are Revolutionizing Business Operations",
    Tagname: ["IT Management", "Cybersecurity and risk", "Database Management"],
    Latest: true,
    Featured: false,
    Trend: false,
  },
  {
    Title: "AI in Agent Studio",
    URL: "/AIinAgentStudio",
    Img: "/assets/Blogs/blogheaders/AIinAgentStudio_Header.webp",
    Desc: "How Conversational AI in Agent Studio Enhances Customer Satisfaction",
    Tagname: ["IT Management", "Cybersecurity and risk", "Database Management"],
    Latest: true,
    Featured: false,
    Trend: false,
  },
  {
    Title: "Workflows with AppStudio",
    URL: "/WorkflowswithAppStudio",
    Img: "/assets/Blogs/blogheaders/WorkflowswithAppStudio_Header.webp",
    Desc: "Elevate Your Operations with AppStudio’s Intelligent Workflow Automation",
    Tagname: ["Database Management", "Cybersecurity and risk"],
    Latest: true,
    Featured: false,
    Trend: false,
  },
  {
    Title: "Agent Studio’s AI Solutions",
    URL: "/AgentStudioAISolutions",
    Img: "/assets/Blogs/blogheaders/AgentStudioAISolutions_Header.webp",
    Desc: "Scaling Customer Support with Agent Studio’s AI-Powered Automation",
    Tagname: ["IT Management", "Cybersecurity and risk", "Database Management"],
    Latest: true,
    Featured: false,
    Trend: false,
  },
  {
    Title: "Customer Satisfaction with Agent Studio",
    URL: "/CustomerSatisfactionwithAgentStudio",
    Img: "/assets/Blogs/blogheaders/CustomerSatisfactionwithAgentStudio_Header.webp",
    Desc: "Enhance Customer Satisfaction with Agent Studio’s Personalized AI Solutions",
    Tagname: ["IT Management", "Cybersecurity and risk", "Database Management"],
    Latest: true,
    Featured: false,
    Trend: false,
  },

  {
    Title: "Fine-Tuning with AI Studio",
    URL: "/FineTuningwithAIStudio",
    Img: "/assets/Blogs/blogheaders/FineTuningwithAIStudio_Header.webp",
    Desc: "Create and Train Custom AI Models Easily with AI Studio",
    Tagname: ["IT Management", "Digisquares Platform", "Database Management"],
    Latest: true,
    Featured: false,
    Trend: false,
  },
  {
    Title: "AI in Knowledge Management",
    URL: "/AIinKnowledgeManagement",
    Img: "/assets/Blogs/blogheaders/AIinKnowledgeManagement_Header.webp",
    Desc: "How AI is Transforming Knowledge Management",
    Tagname: ["IT Management", "AI and Automation"],
    Latest: false,
    Featured: false,
    Trend: true,
  },
  {
    Title: "Impact of AI on Customer Experience",
    URL: "/AIonCustomerExperience",
    Img: "/assets/Blogs/blogheaders/AIonCustomerExperience_Header.webp",
    Desc: "Can AI Truly Enhance Customer Experience? Here's What You Need to Know",
    Tagname: ["Cloud Management", "Cybersecurity and risk"],
    Latest: true,
    Featured: false,
    Trend: true,
  },

  // ---------------3rd session-----------------

  {
    Title: "AI Studio’s Synthetic Data",
    URL: "/AIStudioSyntheticData",
    Img: "/assets/Blogs/blogheaders/AIStudioData_Header.webp",
    Desc: "Accelerate AI Development with Synthetic Data from Digisquares AI Studio",
    Tagname: ["IT Management", "Digisquares Platform", "Database Management"],
    Latest: false,
    Featured: false,
    Trend: false,
  },
  {
    Title: "Personalize AI Models",
    URL: "/PersonalizeAIModels",
    Img: "/assets/Blogs/blogheaders/PersonalizeAIModels_Header.webp",
    Desc: "Customized AI for Every Industry: Transforming Business with AI Studio",
    Tagname: [
      "IT Management",
      "Cybersecurity and risk",
      "Digisquares Platform",
    ],
    Latest: false,
    Featured: true,
    Trend: false,
  },
  {
    Title: "Machine Learning Basics with AI Studio",
    URL: "/MachineLearningBasicswithAI",
    Img: "/assets/Blogs/blogheaders/MachineLearningBasicswithAI_Header.webp",
    Desc: "Discover Machine Learning Basics with AI Studio’s Intuitive Platform",
    Tagname: ["IT Management", "Cybersecurity and risk"],
    Latest: false,
    Featured: true,
    Trend: false,
  },
  {
    Title: "Creating Responsible AI Models",
    URL: "/ResponsibleAIModels",
    Img: "/assets/Blogs/blogheaders/ResponsibleAIModels_Header.webp",
    Desc: "Creating Responsible AI Models with AI Studio’s Ethical Tools",
    Tagname: ["IT Management", "Cybersecurity and risk", "Database Management"],
    Latest: false,
    Featured: false,
    Trend: false,
  },

  // -------------------------------------------------------------------
  // {
  //   Title: "AI in Data-Cloud",
  //   URL: "/AIinDataCloud",
  //   Img: "/assets/AI in DataCloud Main.webp",
  //   Desc: "Many Enterprises Fast-Tracked Their Cloud Migrations in 2020",
  //   Tagname: ["AI and Automation", "Cloud Management", "Database Management"],
  //   Latest: true,
  //   Featured: false,
  //   Trend: false,
  //   // year: 2022,
  // },
  // {
  //   Title: "API Enabled Ecosystem",
  //   URL: "/APIEnabledEcosystem",
  //   Img: "/assets/APIEnabledEcosystemMain.webp",
  //   Desc: "Role of analytics in unlocking the power of API enabled ecosystems",
  //   Tagname: ["Digital Transformation", "IT Management"],
  //   Latest: false,
  //   Featured: true,
  //   Trend: false,
  // },
  // {
  //   Title: "Being a Programmer",
  //   URL: "/BeingaProgrammer",
  //   Img: "/assets/Programmer Main.webp",
  //   Desc: "Being a Programmer",
  //   Tagname: ["IT Management", "Database Management"],
  //   Latest: false,
  //   Featured: false,
  //   Trend: true,
  // },
  // {
  //   Title: "Building Blocks",
  //   URL: "/Buildingblocks",
  //   Img: "/assets/AI-carriere.webp",
  //   Desc: "Six building blocks for successfully implementing AI",
  //   Tagname: ["IT Management", "Digital Transformation"],
  //   Latest: false,
  //   Featured: false,
  //   Trend: true,
  // },
  // {
  //   Title: "Cloud Computing",
  //   URL: "/CloudComputing",
  //   Img: "/assets/The_Top_30_Important_Cloud_Computing_Terms.webp",
  //   Desc: "What is Cloud Computing",
  //   Tagname: ["Cloud Management", "Digisquares Platform"],
  //   Latest: true,
  //   Featured: false,
  //   Trend: false,
  // },
  // {
  //   Title: "Cloud Enabled AI",
  //   URL: "/CloudEnabledAI",
  //   Img: "/assets/CloudEnabledAI Main.webp",
  //   Desc: "How Cloud-Enabled AI will Drive Business Value in the Future",
  //   Tagname: ["Cloud Management", "AI and Automation"],
  //   Latest: false,
  //   Featured: true,
  //   Trend: false,
  // },
  // {
  //   Title: "Cloud Security Risks",
  //   URL: "/CloudSecurityRisks",
  //   Img: "/assets/CloudSecurity1.webp",
  //   Desc: "Minimize the Cloud security risks and threads",
  //   Tagname: ["Cloud Management", "Cybersecurity and risk"],
  //   Latest: false,
  //   Featured: false,
  //   Trend: true,
  // },
  // {
  //   Title: "Database Software",
  //   URL: "/DatabaseSoftware",
  //   Img: "/assets/DatabaseSoftwareMain.webp",
  //   Desc: "Price Indexes for PC Database Software and the Value of Code Compatibility",
  //   Tagname: ["Data Management", "IT Management", "Database Management"],
  //   Latest: false,
  //   Featured: true,
  //   Trend: false,
  // },
  // {
  //   Title: "Deploying AI at scale",
  //   URL: "/Deployingscale",
  //   Img: "/assets/ezgif.com-gif-maker (2).webp",
  //   Desc: "A glimpse into the future of manufacturing can be found at FANUC’s plant in Oshino, Japan.",
  //   Tagname: ["AI and Automation", "IT Management", "Database Management"],
  //   Latest: true,
  //   Featured: false,
  //   Trend: false,
  // },
  // {
  //   Title: "Digital Trends IoT",
  //   URL: "/DigitalTrendsIoT",
  //   Img: "/assets/IoT-Main-Img.webp",
  //   Desc: "Key digital trends shaping the future",
  //   Tagname: [
  //     "Digital Transformation",
  //     "Digisquares Platform",
  //     "Database Management",
  //   ],
  //   Latest: false,
  //   Featured: true,
  //   Trend: false,
  // },
  // {
  //   Title: "GDPR Compliance",
  //   URL: "/GDPRCompliance",
  //   Img: "/assets/DataSecureMainImg.webp",
  //   Desc: "GDPR Compliance to avoid fines",
  //   Tagname: ["Digital Transformation", "IT Management", "Database Management"],
  //   Latest: false,
  //   Featured: false,
  //   Trend: true,
  // },
  // {
  //   Title: "Lowcode at AI",
  //   URL: "/LowcodeatAI",
  //   Img: "/assets/LowCodeMain.webp",
  //   Desc: "Low code may open AI doors for many businesses",
  //   Tagname: ["Digisquares Platform", "AI and Automation"],
  //   Latest: true,
  //   Featured: false,
  //   Trend: false,
  // },
  // {
  //   Title: "Managed Databases",
  //   URL: "/ManagedDatabases",
  //   Img: "/assets/Database Main.webp",
  //   Desc: "Benefits of Managed Databases",
  //   Tagname: ["Database Management", "Digisquares Platform"],
  //   Latest: false,
  //   Featured: false,
  //   Trend: true,
  // },
  // {
  //   Title: "Multi Cloud Governance",
  //   URL: "/MultiCloudGovernance",
  //   Img: "/assets/GovernanceComp.webp",
  //   Desc: "AI-powered Multi-Cloud Governance at Scale",
  //   Tagname: ["Cloud Management", "AI and Automation", "Governance"],
  //   Latest: true,
  //   Featured: false,
  //   Trend: false,
  // },
  // {
  //   Title: "Planning your code",
  //   URL: "/Planningyourcode",
  //   Img: "/assets/1_jIt9fOkdMWqgeb07WkjbOA.webp",
  //   Desc: "Planning Your Code",
  //   Tagname: ["Digisquares Platform", "IT Management"],
  //   Latest: false,
  //   Featured: true,
  //   Trend: false,
  // },
  // {
  //   Title: "Real Time DB",
  //   URL: "/RealTimeDB",
  //   Img: "/assets/Manageddatabase_3.webp",
  //   Desc: "Real time database technology and its applications",
  //   Tagname: ["Digisquares Platform", "Database Management"],
  //   Latest: false,
  //   Featured: false,
  //   Trend: true,
  // },
  // {
  //   Title: "Revolutionizing",
  //   URL: "/Revolutionizing",
  //   Img: "/assets/AI-foto-generale.webp",
  //   Desc: "What Is GPT-3 And Why Is It Revolutionizing Artificial Intelligence",
  //   Tagname: ["AI and Automation", "Cloud Management"],
  //   Latest: true,
  //   Featured: false,
  //   Trend: false,
  // },
  // {
  //   Title: "Security Privacy of Blockchain",
  //   URL: "/SecurityPrivacyofBlockchain",
  //   Img: "/assets/BlockChainMain.webp",
  //   Desc: "Additional Security and Privacy Properties of Blockchain",
  //   Tagname: ["Cybersecurity and risk", "Digisquares Platform"],
  //   Latest: false,
  //   Featured: true,
  //   Trend: false,
  // },
  // {
  //   Title: "Social Engineering",
  //   URL: "/SocialEngineering",
  //   Img: "/assets/20200724-brandon2-karen.webp",
  //   Desc: "Social Engineering",
  //   Tagname: ["IT Management", "Digisquares Platform", "Governance"],
  //   Latest: false,
  //   Featured: false,
  //   Trend: true,
  // },
  // {
  //   Title: "Technology Leaders",
  //   URL: "/TechnologyLeaders",
  //   Img: "/assets/shutterstock_430052296-897x500.webp",
  //   Desc: "What are the New Expectations from Technology Leaders",
  //   Tagname: ["Digital Transformation", "IT Management"],
  //   Latest: true,
  //   Featured: false,
  //   Trend: false,
  // },
  // {
  //   Title: "Top Database Security Threats",
  //   URL: "/TopDatabaseSecurityThreats",
  //   Img: "/assets/SecurityThreatsMain.webp",
  //   Desc: "Top Ten Database Security Threats",
  //   Tagname: ["Cybersecurity and risk", "Database Management"],
  //   Latest: false,
  //   Featured: true,
  //   Trend: false,
  // },
  // {
  //   Title: "The digitalization of production chains",
  //   URL: "/Digitalizationchains",
  //   Img: "/assets/Digitalization-Main.webp",
  //   Desc: "The digitalization of production chains",
  //   Tagname: ["Digital Transformation", "Digisquares Platform"],
  //   Latest: false,
  //   Featured: false,
  //   Trend: true,
  // },
  // {
  //   Title: "Driving Digital Transformation",
  //   URL: "/DrivingDigitalTransformation",
  //   Img: "/assets/Driving Digital Transformation.webp",
  //   Desc: "Driving Digital Transformation",
  //   Tagname: ["Digital Transformation", "Digisquares Platform"],
  //   Latest: true,
  //   Featured: false,
  //   Trend: false,
  // },
  // {
  //   Title: "Reinventing Data Warehouse",
  //   URL: "/ReinventingDataWarehouse",
  //   Img: "/assets/Data-Warehouse.webp",
  //   Desc: "The harsh reality of data warehousing is that conventional solutions are simply too costly",
  //   Tagname: ["Database Management", "Digisquares Platform"],
  //   Latest: false,
  //   Featured: false,
  //   Trend: true,
  // },
  // {
  //   Title: "Key Parameters to be considered for Cloud Migration",
  //   URL: "/KeyParamCloudMigration",
  //   Img: "/assets/CloudMigration.webp",
  //   Desc: "Choosing the right cloud provider is the first step for any organization planning to adopt public cloud services.",
  //   Tagname: ["Cloud Management", "Digisquares Platform"],
  //   Latest: true,
  //   Featured: false,
  //   Trend: false,
  // },
  // {
  //   Title: "Understanding Comprehensive Database Security",
  //   URL: "/ComprehensiveDbSecurity",
  //   Img: "/assets/DBSecurityMain.webp",
  //   Desc: "Understanding Comprehensive Database Security",
  //   Tagname: ["Database Management", "Cybersecurity and risk"],
  //   Latest: true,
  //   Featured: false,
  //   Trend: false,
  // },
  // {
  //   Title:
  //     "Surveyed enterprises most commonly used software as a service for automation",
  //   URL: "/CybersecurityinDigitalEra",
  //   Img: "/assets/Saas-Main.webp",
  //   Desc: "Priorities in attempting to secure software as a service",
  //   Tagname: ["IT Management", "Cybersecurity and risk", "Database Management"],
  //   Latest: false,
  //   Featured: true,
  //   Trend: false,
  // },
  // {
  //   Title:
  //     "Security-as-a-Service Transformation for State and Local Government",
  //   URL: "/SaasforGovt",
  //   Img: "/assets/SaasGovtMain.webp",
  //   Desc: "Traditionally, each State agency built out its own network and designed its own security architecture.",
  //   Tagname: ["IT Management", "Governance"],
  //   Latest: false,
  //   Featured: false,
  //   Trend: true,
  // },
  // {
  //   Title: "Top Tips To Speed Up Your Website",
  //   URL: "/SpeedupWebsite",
  //   Img: "/assets/WebsiteSpeed(5).webp",
  //   Desc: "Tools such as WebPageTest or Pingdom will show you basic performance metrics.",
  //   Tagname: ["IT Management", "Digital Transformation"],
  //   Latest: false,
  //   Featured: true,
  //   Trend: false,
  // },
  // {
  //   Title: "Accelerate Digital Transformation with Low-Code",
  //   URL: "/LowCode",
  //   Img: "/assets/LowCode-1.webp",
  //   Desc: "Low-code platforms make it possible to design and deploy applications quickly.",
  //   Tagname: ["Digisquares Platform", "Digital Transformation"],
  //   Latest: true,
  //   Featured: false,
  //   Trend: false,
  // },
  // {
  //   Title: "Role of Low-code/No-code Development in Democratizing Automation",
  //   URL: "/LowCodeAutomation",
  //   Img: "/assets/LowCodeAutomation1.webp",
  //   Desc: "Low-code/No-code automation tools enable people with limited or no coding abilities to automate repeatable business processes",
  //   Tagname: [
  //     "IT Management",
  //     "Digisquares Platform",
  //     "Digital Transformation",
  //   ],
  //   Latest: false,
  //   Featured: false,
  //   Trend: true,
  // },
  // {
  //   Title: "Low code digital automation platform for Connected Banking",
  //   URL: "/LowcodeinBanking",
  //   Img: "/assets/LowcodeBanking1.webp",
  //   Desc: "Low-code platforms are generally focused on the developer experience, streamlining application development by automating tasks from initial design to iteration.",
  //   Tagname: ["Digisquares Platform", "Digital Transformation"],
  //   Latest: true,
  //   Featured: false,
  //   Trend: false,
  // },
  // {
  //   Title: "Enterprise Low-code and Hyper-automation",
  //   URL: "/EnterpriseLowcode",
  //   Img: "/assets/HyperAutomation1.webp",
  //   Desc: "low-code applications can be integrated with cloud services and other applications, thus creating a broader ecosystem.",
  //   Tagname: [
  //     "Digisquares Platform",
  //     "Digital Transformation",
  //     "IT Management",
  //   ],
  //   Latest: false,
  //   Featured: true,
  //   Trend: false,
  // },
  // {
  //   Title: "Accelerating Customer Communications",
  //   URL: "/AcceleratingCustomer",
  //   Img: "/assets/CustomerCommunication1.webp",
  //   Desc: "Low Code is a concept originating in software development which allows users to dynamically create new applications with little or no requirement for specialist skills or IT support.",
  //   Tagname: [
  //     "Digisquares Platform",
  //     "Digital Transformation",
  //     "IT Management",
  //   ],
  //   Latest: false,
  //   Featured: false,
  //   Trend: true,
  // },
];
